name: Deploy to EC2

on:
  push:
    branches: [Prod]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~
            mkdir NENE
            if [ ! -d "CurlUp-Frontend" ]; then
              git clone git@github.com:n4naynay/CurlUp-Frontend.git
            fi
            cd CurlUp-Frontend
            git pull origin Prod
        
            sudo docker-compose down || true
            sudo docker-compose up --build -d
          EOF
          
